"""Centralized application constants to prevent inline magic numbers."""

# Pagination limits
DEFAULT_PAGE_SIZE = 25
ALLOWED_PAGE_SIZES = [10, 25, 50, 100]
MAX_PAGE_SIZE_SAFE = 500

# File size thresholds (in bytes)
MAX_MEDIA_VIDEO_SIZE = 100 * 1024 * 1024  # 100 MB
MAX_MEDIA_AUDIO_SIZE = 50 * 1024 * 1024   # 50 MB
MAX_MEDIA_PHOTO_SIZE = 10 * 1024 * 1024   # 10 MB

# Timeouts & Retries
HTTP_CONNECT_TIMEOUT_SEC = 10
HTTP_READ_TIMEOUT_SEC = 60
MUSETALK_DEFAULT_TIMEOUT_SEC = 1800
MAX_EXTERNAL_RETRIES = 3
RETRY_BACKOFF_FACTOR = 1.5

# Credit consumption per action
CREDITS_COST_PODCAST_ANALYZE = 10
CREDITS_COST_PODCAST_HOOKS = 5
CREDITS_COST_PODCAST_CLIP = 15
CREDITS_COST_CAROUSEL_GENERATE = 5
CREDITS_COST_CAROUSEL_RENDER = 10
CREDITS_COST_REMAKE_OVERLAY = 15
CREDITS_COST_REMAKE_LIPSYNC = 30

# Rate limits (requests per minute window)
RATE_LIMIT_AUTH_PER_MINUTE = 10
RATE_LIMIT_AI_PER_MINUTE = 15
RATE_LIMIT_UPLOAD_PER_MINUTE = 20
RATE_LIMIT_GENERAL_PER_MINUTE = 120

# AI defaults
DEFAULT_AI_PROVIDER = "gemini"
DEFAULT_AI_MODEL = "gemini-1.5-flash"
DEFAULT_AI_TEMPERATURE = 0.7
DEFAULT_AI_MAX_TOKENS = 2048

# Content plan formats
CONTENT_PLAN_FORMATS = ("CAROUSEL", "PODCAST_CLIP", "REMAKE", "REELS")

